// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdicionarRegistro(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['AdicionarRegistro'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function ListarRegistros() {
  return window['go']['main']['App']['ListarRegistros']();
}

export function ListarVendedores() {
  return window['go']['main']['App']['ListarVendedores']();
}
