// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AdicionarRegistro(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number,arg9:number,arg10:number,arg11:number,arg12:string):Promise<void>;

export function ListarRegistros():Promise<Array<Record<string, any>>>;

export function ListarVendedores():Promise<Array<main.Vendedor>>;
